name = "TinyMPC"
uuid = "c2f9f121-b1d5-4a6a-b362-7f2de3b7e0f1"
version = "0.2.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ForwardDiff = "1.0.1"
Plots = "1.0"
julia = "1.6"

[[authors]]
name = "Sam Schoedel"
email = "seschoedel@gmail.com"
[[authors]]
name = "Khai Nguyen"
email = "khai.nx1201@gmail.com"
[[authors]]
name = "Moises Mata"
email = "moises.mata.t@gmail.com"
[[authors]]
name = "Ishaan Mahajan"
email = "ishaanamahajan@gmail.com"
