name = "TinyMPC"
uuid = "c2f9f121-b1d5-4a6a-b362-7f2de3b7e0f1"
authors = [
  { name="Sam Schoedel", email="seschoedel@gmail.com" },
  { name="Khai Nguyen", email="khai.nx1201@gmail.com" },
  { name="Moises Mata", email="moises.mata.t@gmail.com"},
  { name="Ishaan Mahajan", email="ishaanamahajan@gmail.com" },]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"
Plots = "1.0"